### ISSUE TITLE
Comment sorting only affects the latest 5 comments

### ISSUE THREAD

**Issue by dionysius** [studentquiz/moodle-mod_studentquiz#276]
Once a question has more than 5 comments, the sorting options only sort the 5 latest comments. I think the sorting should affect all comments to the question, not only the last 5 ones.

Steps to reproduce:
- For a question create >5 comments (no need for replies). I had 26, one for each character in the alphabet.
- Refresh the page
- The page now shows the last 5 comments (to not overload the page). There's a button to show all, but we don't use it now
- Play around with the sorting links, they only sort those 5 questions, ignoring the hidden comment

cc @lamtranb @HuongNV13 @SangNguyenAnh

**Comment by HuongNV13** [comment]
Hi @dionysius,
We will investigate this issue and get back to you soon.

FYI: @lamtranb  is not the OU Team anymore.

Thanks,

**Comment by dionysius** [comment]
Thanks. Absolutely no hurry, I labelled this as minor.

**Comment by dionysius** [comment]
fixed by https://github.com/studentquiz/moodle-mod_studentquiz/pull/318
