### ISSUE TITLE
Function return type that would be required for Moodle 4.0

### ISSUE THREAD

**Issue by marcusgreen** [studentquiz/moodle-mod_studentquiz#369]
I installed on an alpha of Moodle 4.0 and there are base classes that have function return types. The journey to 4.0 can be started by adding those to the existing code. I will create a pull that makes that start.

**Comment by timhunt** [comment]
Marcus, we have our own plans to update StudentQuiz to 4.0 - once the 4.0 question bank changes have finised landing, which they have not yet. Therefore, please can you wait. External pull requests would not be helpful at this time. Thanks.

**Comment by marcusgreen** [comment]
I created the pull anyway so you can see what I was experimenting with. Feel free to ignore, delete, decline etc etc
