### ISSUE TITLE
"Daily" and/or "Weekly" appear untranslated in e-mail notifications

### ISSUE THREAD

**Issue by lucaboesch** [studentquiz/moodle-mod_studentquiz#373]
"Daily" and/or "Weekly" string is passed to the mailing mechanism without being localized resulting in phrases such as 

Dies ist Ihre Daily Ausgabe der Benachrichtigungen für die eHealth StudentQuiz StudentQuiz-Aktivität, hier verfügbar:https://moodle.moodle.moodle/mod/studentquiz/view.php?cmid=1425290

The code that causes this is here, probably: https://github.com/studentquiz/moodle-mod_studentquiz/blob/master/classes/task/send_digest_notification_task.php#L77

Best,
Luca

**Comment by timhunt** [comment]
Thanks Luca. We'll get that fixed.
