### ISSUE TITLE
Questions dissapeared after uprade to v4.6.2 when keeping group restriction

### ISSUE THREAD

**Issue by miroi** [studentquiz/moodle-mod_studentquiz#405]
Hello !

In StudentQuiz students created questions, which were visible. But after upgrade to v4.6.2 all questions disappeared, but remained hidden in the question bank.

The StudentQuiz was restricted to be visible to a specific group only. I removed the group restriction and all the questions show up ! Again I restricted StudentQuiz to a specific group and questions remained visible.

Has somebody encountered such experience ?  Please close this ticket after some time.

**Comment by timhunt** [comment]
I don't konw what happened here. However, no-one else has hit this, so I will just close it.

Thanks for taking the time to report yoru issue.
