### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [studentquiz/moodle-mod_studentquiz#410]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by timhunt** [comment]
It is being worked on in #390. Big job! Hopefully we are nearly there. If you are brave, you can try using the code from that pull request, to help us test it, and let us know any issues you find.

**Comment by acquaalta** [comment]
Thanks, Tim :-)
