### ISSUE TITLE
Update to V5.0.0: Writing to database error

### ISSUE THREAD

**Issue by mattgig** [studentquiz/moodle-mod_studentquiz#418]
When I try to update an existing StudentQuiz installation to version V5.0.0 under Moodle 4.0.4 I get a writing to database error:

Debug info: Field 'questionid' doesn't have a default value
INSERT INTO MDL_studentquiz_state_history (userid,state,timecreated) VALUES(?,?,?)
[array (
0 => 2,
1 => 2,
2 => 1593437350,
)]
Error code: dmlwriteexception

*I use a different prefix instead of MDL.

In case you need some additional information I can investigate further in a few hours.

**Comment by timhunt** [comment]
What is also odd is that I can't see where in the upgrade code is anything that would lead to that. If you had a stack trace for the error, that would help.

Anyway, I am glad it worked the second time.

Shall we just close this?

**Comment by mattgig** [comment]
Yes, please do so. Sorry for the inconvenience.

**Comment by timhunt** [comment]
No worries. Thank you for taking the time to contribute to StudentQuiz, even if it turned out to be a false alarm this time.
