### ISSUE TITLE
Backup and Restore with tags fails 

### ISSUE THREAD

**Issue by RahelPhasen** [studentquiz/moodle-mod_studentquiz#419]
Hi, 
we found an error when using tags in combination with the studentquiz plugin. 
Steps to reproduce:
1) Create an activity with one question
2) Assign a few tags to this question in the edit/add form 
3) Do a backup and restore of this activity in this course
4) Have a look into this duplicated course; You'll see the assigned tags in the overview table but as soon as you try to edit the question because you'd like to delete one of the existing tags, they aren't there anymore. 

Here's how it looks like:

![image](https://user-images.githubusercontent.com/81369338/191760437-045f422d-47de-4fc7-8315-cc9c7a639595.png)
![image](https://user-images.githubusercontent.com/81369338/191760461-cf041e14-15e1-462d-8482-d92bbd00c160.png)
(The second picture shows the edit form of the second question calles "Wetter") 

So the tags aren't listed in the edit mode. I not sure if I found the mistake in the code. I feel like there is an Issue when doing the backup. I think the tags aren't getting assinged the right context.

**Comment by timhunt** [comment]
Can I just check, which version of StudentQuiz are you using, with which version of Moodle? Thanks.

**Comment by RahelPhasen** [comment]
We are using Moodle 3.11.8 and or StudentQuiz version is v4.5.0.

**Comment by oucnelson** [comment]
Confirmed.
Using the latest version of StudentQuiz on our Moodle 4.0 server, I can confirm that the tag is 'lost' on the Edit question form within StudentQuiz, despite being visible in the StudentQuiz table and in the question bank for the restored activity.
We will try to fix this defect as soon as we can.
