### ISSUE TITLE
Missing error message when no wildcard value is selected

### ISSUE THREAD

**Issue by Rexo99** [studentquiz/moodle-mod_studentquiz#443]
While testing the StudentQuiz plugin for our Moodle 4.x release, I encountered a usability problem. 
The question type "Calculated simple" in particular took me far too long to get right. Trying this type of question without any prior knowledge led to the following problem.
You can get pretty far by just submitting your question and learning from the error message what to do next. Except for the wildcard assignment. If you don't click on the "Find wildcards {x...} present in the correct answer formulas"-button, you won't get any error messages or anything else to indicate that something went wrong when you submit.
This is not very intuitive, especially when you are used to getting to the next page, as in the "Calculated" question type.
I would recommend a simple prompt or error message, like the one you get when you have not declared a wildcard. A simple message telling the user what is missing and what to do.

**Comment by dionysius** [comment]
Studentquiz forwards you to the moodle question creation page for displaying the form and has no influence what happens within. If you observe the same usability issue when creating such question type in a quiz activity (which i assume) I suggest filing an issue on the [moodle issue tracker](https://tracker.moodle.org/issues/). This also means it depends on your moodle version.

**Comment by timhunt** [comment]
Yes. Closing this issue, since it is in the wrong place.

**Comment by Rexo99** [comment]
Thanks for the quick reply. I will look into it.
