### ISSUE TITLE
Exception - Class "qbank_previewquestion\preview_action_column" not found

### ISSUE THREAD

**Issue by mcassisa** [studentquiz/moodle-mod_studentquiz#475]
StudentQuiz v5.1.0 on Moodle 4.3+ (Build: 20231027)' raises an error

Class "qbank_previewquestion\preview_action_column" not found

after successfully creating a StudentQuiz element, when trying to add questions. 
This prevents to go any further

**Comment by timhunt** [comment]
Yes. This is being worked on here: https://github.com/studentquiz/moodle-mod_studentquiz/pull/467
