### ISSUE TITLE
Hard coded language string?

### ISSUE THREAD

**Issue by cdipe** [studentquiz/moodle-mod_studentquiz#479]
When taking a studentquiz with Swedish language selected there is an English string "Your answer is correct."
I have searched the language pack and the translations are done as far as I can find.

<img width="990" alt="image" src="https://github.com/studentquiz/moodle-mod_studentquiz/assets/14754240/ed4eb178-4657-4c34-bec4-2ad19b93db1f">

<img width="871" alt="image" src="https://github.com/studentquiz/moodle-mod_studentquiz/assets/14754240/75e0e282-491e-467c-abf9-41a4bbccf828">

**Comment by cdipe** [comment]
Sorry: Moodle 4.1.7 and StudentQuiz v5.2.0 (2023081702)

**Comment by timhunt** [comment]
That string is not coming from StudentQuiz.

That is the default value (for an English user) of the 'Combined feedback' that is part of the settings for a mulitple choice question. Note that that default text should be in the language of the user who created the question. (See, for example https://qa.moodledemo.net/question/bank/editquestion/question.php?courseid=2&qtype=multichoice&category=2.)

So, I will close this.
