### ISSUE TITLE
Can't open StudentQuiz Activity, error message "Exception - Class "qbank_previewquestion\preview_action_column" not found"

### ISSUE THREAD

**Issue by smhearty** [studentquiz/moodle-mod_studentquiz#480]
Hi. 

I've installed StudentQuiz, but I'm getting error messages. 
*** 
- Exception - Class "qbank_previewquestion\preview_action_column" not found
### Stack Trace: 
- line 26 of /mod/studentquiz/classes/question/bank/preview_column.php: Error thrown
- line 46 of /mod/studentquiz/classes/question/bank/studentquiz_bank_view.php: call to require_once()
- line 147 of /lib/classes/component.php: call to include_once()
- line 166 of /mod/studentquiz/viewlib.php: call to core_component::classloader()
- line 119 of /mod/studentquiz/viewlib.php: call to mod_studentquiz_view->load_questionbank()
- line 57 of /mod/studentquiz/view.php: call to mod_studentquiz_view->__construct()
*** 
I'm running Moodle 4.3.1 with StudentQuiz v5.2.0 (2023081702). I've tried deleting and reinstalling the plugin. I have also tried a couple of different themes (*generally using LearnR, but have switched to Boost for troubleshooting purposes*). 

I've attempted to Restore a StudentQuiz activity that was backed up from an earlier version of Moodle. I have also attempted to create a brand new StudentQuiz activity. I'm getting the same error message. Note that StudentQuiz does allow me to create an activity, but clicking on the activity results in errors (and much sadness). 
<img width="894" alt="image" src="https://github.com/studentquiz/moodle-mod_studentquiz/assets/5431576/d4f1778e-c9d2-4b0c-be00-085f7c4be85b">
*** 
If I open the Question Bank, I can create a question. However, going back to the StudentQuiz tab results in the same error. 

Any suggestions?

**Comment by smhearty** [comment]
After a bit of digging, I did find a post about the required changes currently under review. Thus, I believe that the next release will resolve this issue.

**Comment by timhunt** [comment]
You digging unearthed the correct answer :-)
