### ISSUE TITLE
Error in moodle 4.3.3

### ISSUE THREAD

**Issue by nuria2c** [studentquiz/moodle-mod_studentquiz#484]
We know you are working on the upgrade to Moodle 4.3.x but we have tried your plugin (version v5.2.0,) in a Moodle 4.3.3+ (Build: 20240320) Boost Union theme, after update from Moodle 4.2, and it gives us this error:

Exception - Class "qbank_previewquestion\preview_action_column" not found.

with the dubug, the error is 

Stack trace:
line 26 of /mod/studentquiz/classes/question/bank/preview_column.php: Error thrown
line 46 of /mod/studentquiz/classes/question/bank/studentquiz_bank_view.php: call to require_once()
line 147 of /lib/classes/component.php: call to include_once()
line 166 of /mod/studentquiz/viewlib.php: call to core_component::classloader()
line 119 of /mod/studentquiz/viewlib.php: call to mod_studentquiz_view->load_questionbank()
line 57 of /mod/studentquiz/view.php: call to mod_studentquiz_view->__construct()

The "Settings", "Statistics", "Ranking" and "Question bank" options seem are working correctly.

**Comment by timhunt** [comment]
Have you tried the latest code from the Main branch here?

**Comment by nuria2c** [comment]
we tried the last stable version in the moodle plugins website. Is not this one?

**Comment by timhunt** [comment]
The version in the Moodle plugins database is old, and only supports up to 4.2.

We have newer code here, but I need to find time to publish it

**Comment by nuria2c** [comment]
Ok. Next week will try this Github version.
Thanks

**Comment by JAUYEB** [comment]
Dear timhunt, 

This information is very valuable and we do not know it. 

Seeing here that the plugin has not had any changes on github for weeks and the latest version in moodle/plugins is for 4.2 we thought it was being abandoned due to lack of time. We were wrong!

So that it doesn't happen to us again here on github, where can we check the latest compatible version of Moodle?

I mention this because I don't know how to find it, everything I read here is max Moodle 4.2....

Thanks for your time and for a fantastic plugin!!

**Comment by tadeucaldas** [comment]
> The version in the Moodle plugins database is old, and only supports up to 4.2.
> 
> We have newer code here, but I need to find time to publish it

Hi! First of all.. probably the greatest moodle activity plugin for student engagement ever made.. tks a lot!

Second.. do you guys have a release date for this? I´m asking becouse a manage a moodle instance that holds over 2k students every semester. We´d love to try your plugin as soon as possible, but we´re on 403 already. 

To install the branch version all i need to do is download the source code zip and upload it as an plugin zip file?

**Comment by nuria2c** [comment]
Hi Tim,
We've tried the last version of Github under 4.3 and it works correctly. Thanks!

After uploaded it i saw the version is the same published in Moodle plugins 5.2.0. Is that correct?
